name: iOS Build and Test

on:
  pull_request:
    branches:
      - main
jobs:
  buildAndTest:
    name: Build and Test the app
    runs-on: macos-13
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build and test
        run: |
          xcodebuild \
            -project SwiftIslandApp.xcodeproj \
            -scheme SwiftIsland \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=Any iOS Simulator Device,OS=17.0' \
            test