name: iOS Build and Test

on:
  pull_request:
    branches:
      - main
jobs:
  buildAndTest:
    name: Build and Test the app
    runs-on: macos-13
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Select correct xcode
        run: sudo xcode-select -s '/Applications/Xcode_14.3.1.app'
      - name: Create dummy Secrets.json file
        run: echo '{ }' >> SwiftIslandApp/Resources/Secrets.json
      - name: Build and test
        run: |
          xcodebuild \
            -project SwiftIslandApp.xcodeproj \
            -scheme SwiftIsland \
            -destination 'platform=iOS Simulator,name=iPhone 14'
            test