name: iOS Build and Test

on:
  pull_request:
    branches:
      - main
jobs:
  buildAndTest:
    runs-on: macos-12
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build and test
        run: |
          xcodebuild \
            -project SwiftIslandApp.xcodeproj \
            -scheme SwiftIsland \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14 pro,OS=16.4' \
            test